# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-cart
  name: api-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cart
  strategy: {}
  template:
    metadata:
      labels:
        app: api-cart
    spec:
      containers:
      - image: api-cart:v1
        name: api-cart
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        resources: {}
      restartPolicy: Always
status: {}
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-cart
  name: api-cart
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31404
  selector:
    app: api-cart
  type: NodePort
status:
  loadBalancer: {}